global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'credicard'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['credicard:50051']