micronaut:
  application:
    name: credicard
datasources:
  default:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:credicard}
    driverClassName: org.postgresql.Driver
    username: admin
    password: abc123
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

external.financialanalysis.url: http://${ANALYSIS_HOST:localhost}:${ANALYSIS_PORT:9999}
